# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = [
    # "intensive_apps",
]

# Packages to be installed via the native package manager.
[managers.system]
items = [
  'ModemManager',
  'NetworkManager',
  'NetworkManager-adsl',
  'NetworkManager-bluetooth',
  'NetworkManager-config-connectivity-fedora',
  'NetworkManager-ppp',
  'NetworkManager-wifi',
  'NetworkManager-wwan',
  'PackageKit-command-not-found',
  'PackageKit-gstreamer-plugin',
  'aajohan-comfortaa-fonts',
  'ab-download-manager',
  'acl',
  'adwaita-gtk2-theme',
  'adwaita-mono-fonts',
  'adwaita-sans-fonts',
  'akonadi-server',
  'akonadi-server-mysql',
  'alien',
  'alsa-firmware',
  'alsa-sof-firmware',
  'alsa-ucm',
  'alsa-utils',
  'amd-gpu-firmware',
  'amd-ucode-firmware',
  'anda',
  'anda-srpm-macros',
  'android-tools',
  'apparmor-parser',
  'apparmor-utils',
  'apr',
  'apr-util',
  'aria2',
  'ark',
  'at',
  'at-spi2-atk',
  'at-spi2-core',
  'atheros-firmware',
  'attr',
  'atuin',
  'audiocd-kio',
  'audit',
  'authselect',
  'b43-fwcutter',
  'b43-openfwwf',
  'bash',
  'bash-color-prompt',
  'bash-completion',
  'bat',
  'bc',
  'bind-utils',
  'bitstream-vera-fonts-all',
  'bitstream-vera-sans-fonts',
  'bitstream-vera-sans-mono-fonts',
  'bitstream-vera-serif-fonts',
  'bitwarden',
  'bleachbit',
  'blobdrop',
  'blobdrop-fish-completion',
  'bluedevil',
  'bluetui',
  'bluez-cups',
  'bottles',
  'bottom',
  'brave-browser',
  'brcmfmac-firmware',
  'breeze-icon-theme',
  'brightnessctl',
  'brltty',
  'bsdtar',
  'btop',
  'btrfs-progs',
  'bzip2',
  'cargo',
  'cargo-rpm-macros',
  'cascadia-fonts-all',
  'cascadiacode-nerd-fonts',
  'cascadiamono-nerd-fonts',
  'chkconfig',
  'chrony',
  'cifs-utils',
  'cirrus-audio-firmware',
  'clang',
  'clang20-libs',
  'clang20-resource-filesystem',
  'cmake',
  'code',
  'colord',
  'colord-kde',
  'compsize',
  'containerd.io',
  'copyq',
  'coreutils',
  'cpio',
  'cpu-x',
  'cpufetch',
  'crontabs',
  'cryptsetup',
  'cudatext',
  'cups',
  'cups-browsed',
  'cups-filters',
  'cups-pk-helper',
  'curl',
  'cyrus-sasl-plain',
  'dbeaver-ce',
  'dbus',
  'default-editor',
  'default-fonts-cjk-mono',
  'default-fonts-cjk-sans',
  'default-fonts-cjk-serif',
  'default-fonts-core-math',
  'default-fonts-core-mono',
  'default-fonts-core-sans',
  'default-fonts-core-serif',
  'default-fonts-other-mono',
  'default-fonts-other-sans',
  'default-fonts-other-serif',
  'dejavu-sans-fonts',
  'dejavu-sans-mono-fonts',
  'dejavu-serif-fonts',
  'deltarpm',
  'detect-it-easy',
  'devtoys',
  'devtoys-cli',
  'dhcp-client',
  'diffstat',
  'distribution-gpg-keys',
  'distrobox',
  'dnf-utils',
  'dnf5',
  'dnf5-plugins',
  'dnfdaemon',
  'dnscrypt-proxy',
  'dnsmasq',
  'docker-buildx-plugin',
  'docker-ce',
  'docker-ce-cli',
  'docker-ce-rootless-extras',
  'docker-compose-plugin',
  'dolphin',
  'dos2unix',
  'dosfstools',
  'dotnet-sdk-10.0',
  'doublecmd-qt6',
  'doxygen',
  'dracut-config-rescue',
  'dracut-live',
  'dracut-network',
  'ds-inhibit',
  'e2fsprogs',
  'ed',
  'efibootmgr',
  'element-desktop',
  'elisa-player',
  'epson-inkjet-printer-escpr2',
  'epson-printer-utility',
  'ethtool',
  'exfatprogs',
  'falcond',
  'fastfetch',
  'fd-find',
  'fedora-repos',
  'fedora-rpm-macros',
  'fedpkg',
  'ffmpeg-devel',
  'ffmpegthumbnailer',
  'ffmpegthumbs',
  'figma-linux',
  'file',
  'filelight',
  'filesystem',
  'firewall-config',
  'firewalld',
  'flac-libs',
  'flatpak',
  'flatpak-kcm',
  'flatpost',
  'floorp',
  'fontforge',
  'fonts-rpm-macros',
  'fonts-rpm-templates',
  'foomatic',
  'foomatic-db-ppds',
  'fooyin',
  'fpaste',
  'fprintd-pam',
  'fsearch',
  'fuse',
  'fwupd',
  'fzf',
  'gamemode',
  'gap-srpm-macros',
  'gcc-c++',
  'gcc-gfortran',
  'gcm-core',
  'geist-font',
  'geist-font-mono',
  'gettext',
  'gfs2-utils',
  'ghc-mountpoints',
  'ghostscript',
  'gimp',
  'git',
  'git-delta',
  'glibc',
  'glibc-all-langpacks',
  'gnome-logs',
  'gnupg2',
  'gnupg2-dirmngr',
  'gnupg2-g13',
  'gnupg2-gpg-agent',
  'gnupg2-gpgconf',
  'gnupg2-keyboxd',
  'gnupg2-scdaemon',
  'gnupg2-utils',
  'gnupg2-verify',
  'gnupg2-wks',
  'gnuplot',
  'go-rpm-macros',
  'golang',
  'google-carlito-fonts',
  'google-crosextra-caladea-fonts',
  'google-droid-sans-fonts',
  'google-noto-fonts-all',
  'google-noto-sans-sunuwar-fonts',
  'google-noto-serif-fonts',
  'google-noto-serif-hentaigana-fonts',
  'google-noto-serif-hentaigana-vf-fonts',
  'google-noto-serif-todhri-fonts',
  'google-roboto-condensed-fonts',
  'google-roboto-fonts',
  'google-roboto-mono-fonts',
  'google-roboto-slab-fonts',
  'gpgverify',
  'grsync',
  'grub2-efi-ia32',
  'grub2-efi-ia32-cdboot',
  'grub2-efi-x64',
  'grub2-efi-x64-cdboot',
  'grub2-pc',
  'grub2-tools',
  'grub2-tools-efi',
  'grub2-tools-extra',
  'grubby',
  'gstreamer1',
  'gstreamer1-plugin-dav1d',
  'gstreamer1-plugin-libav',
  'gstreamer1-plugin-openh264',
  'gstreamer1-plugins-bad-free',
  'gstreamer1-plugins-bad-free-extras',
  'gstreamer1-plugins-base',
  'gstreamer1-plugins-good',
  'gstreamer1-plugins-ugly-free',
  'guestfs-tools',
  'gutenprint',
  'gutenprint-cups',
  'gvisor-tap-vsock',
  'gwenview',
  'harmonoid',
  'haruna',
  'hddtemp',
  'hfsplus-tools',
  'hostname',
  'hplip',
  'hunspell',
  'hyperfine',
  'hyperv-daemons',
  'i2c-tools',
  'ibm-plex-sans-fonts',
  'imhex',
  'info',
  'initial-setup',
  'initial-setup-gui',
  'initial-setup-gui-wayland-plasma',
  'initscripts',
  'inkscape',
  'intel-audio-firmware',
  'intel-gpu-firmware',
  'intel-media-driver',
  'intel-vsc-firmware',
  'iproute',
  'iptables-nft',
  'iptstate',
  'iputils',
  'irqbalance',
  'iscsi-initiator-utils',
  'isomd5sum',
  'iwlegacy-firmware',
  'iwlwifi-dvm-firmware',
  'iwlwifi-mvm-firmware',
  'java-srpm-macros',
  'jetbrains-mono-fonts-all',
  'jetbrains-toolbox',
  'jetbrainsmono-nerd-fonts',
  'json-c',
  'kaccounts-integration-qt6',
  'kaccounts-providers',
  'kamera',
  'kamoso',
  'kate',
  'kbd',
  'kbd-legacy',
  'kcalc',
  'kcharselect',
  'kclock',
  'kcolorchooser',
  'kde-connect',
  'kde-gtk-config',
  'kde-inotify-survey',
  'kde-l10n',
  'kde-nobara',
  'kde-nobara-sddm',
  'kde-partitionmanager',
  'kde-runtime',
  'kde-settings-pulseaudio',
  'kdebugsettings',
  'kdegraphics-thumbnailers',
  'kdenetwork-filesharing',
  'kdeplasma-addons',
  'kdialog',
  'kdnssd',
  'keditbookmarks',
  'keepassxc',
  'kernel',
  'kernel-core',
  'kernel-devel',
  'kernel-modules',
  'kexec-tools',
  'kf6-baloo-file',
  'kf6-kimageformats',
  'kfind',
  'kgpg',
  'khelpcenter',
  'kinfocenter',
  'kio-admin',
  'kjournald',
  'kmenuedit',
  'kmouth',
  'kmplot',
  'konsole',
  'krdp',
  'kscreen',
  'kscreenlocker',
  'ksnip',
  'ksshaskpass',
  'kwalletmanager5',
  'kweather',
  'kwebkitpart',
  'kwin',
  'langpacks-en',
  'less',
  'libICE',
  'libSM',
  'libXtst',
  'libaom',
  'libappindicator-gtk3',
  'libasyncns',
  'libavcodec-freeworld',
  'libcap-devel',
  'liberation-narrow-fonts',
  'libertas-firmware',
  'libexif',
  'libgcc',
  'libheif-freeworld',
  'libi2c',
  'libieee1284',
  'libogg',
  'libportal',
  'libportal-gtk4',
  'libreoffice',
  'libreoffice-opensymbol-fonts',
  'libreswan-minimal',
  'libsndfile',
  'libsodium-devel',
  'libstemmer',
  'libuuid',
  'libva',
  'libva-intel-media-driver',
  'libvarlink',
  'libvirt',
  'libvorbis',
  'libwayland-client',
  'libwayland-server',
  'libxcrypt-compat',
  'libyaml-devel',
  'livesys-scripts',
  'llvm-libs',
  'llvm20-filesystem',
  'llvm20-libs',
  'localsend',
  'logrotate',
  'lrcget',
  'lrzsz',
  'lsof',
  'lvm2',
  'lzo',
  'lzo-devel',
  'lzo-minilzo',
  'mactel-boot',
  'madan-fonts',
  'mailcap',
  'man-db',
  'man-pages',
  'mandoc',
  'manrope-fonts',
  'mariadb-connector-c',
  'mariadb-embedded',
  'mariadb-server',
  'mathjax-main-fonts',
  'mathjax-math-fonts',
  'mcelog',
  'mdadm',
  'media-hoarder',
  'mediainfo',
  'mediainfo-qt',
  'https://mega.nz/linux/repo/Fedora_43/x86_64/megasync-Fedora_43.x86_64.rpm',
  'memtest86+',
  'mesa-dri-drivers',
  'mesa-libGLU',
  'mesa-libOpenCL',
  'mesa-libgallium-freeworld',
  'mesa-va-drivers-freeworld',
  'mesa-vulkan-drivers-freeworld',
  'meson',
  'microcode_ctl',
  'minicom',
  'mise',
  'mission-center',
  'mock-filesystem',
  'mozilla-fira-sans-fonts',
  'mozilla-openh264',
  'mozjs140',
  'mpc-qt',
  'mpv',
  'ms-core-fonts',
  'mscore-fonts',
  'mt7xxx-firmware',
  'mtr',
  'mypaint',
  'mystiq',
  'naps2',
  'ncdu',
  'ncurses',
  'neochat',
  'net-tools',
  'ngtcp2',
  'ngtcp2-crypto-gnutls',
  'nmap-ncat',
  'nobara-controller-config',
  'nobara-login',
  'nobara-login-sysctl',
  'nobara-release-kde',
  'nobara-repos',
  'nobara-updater',
  'nobara-welcome',
  'nomacs',
  'nss-mdns',
  'ntfs-3g',
  'ntfsprogs',
  'numactl',
  'nvme-cli',
  'nxpwireless-firmware',
  'obs-studio',
  'ocl-icd',
  'oh-my-posh',
  'okular',
  'onefetch',
  'onlyoffice-desktopeditors',
  'onlyoffice-repo',
  'open-sans-fonts',
  'open-vm-tools-desktop',
  'openh264',
  'openrgb',
  'opensc',
  'openssh-clients',
  'openssh-server',
  'openssl',
  'openssl-libs',
  'orca',
  'pam-kwallet',
  'papirus-folders',
  'papirus-icon-theme',
  'papirus-icon-theme-dark',
  'paps',
  'parted',
  'pass',
  'passwdqc',
  'patch',
  'patchutils',
  'pavucontrol-qt',
  'pciutils',
  'pcsc-lite',
  'pcsc-lite-ccid',
  'pdfstudioviewer',
  'pea-qt6',
  'peazip-qt6',
  'perl-Clone-PP',
  'perl-Hash-Util',
  'perl-Sys-Hostname-Long',
  'perl-fields',
  'phonon-qt6-backend-vlc',
  'picocrypt-ng',
  'pinentry-qt',
  'pinfo',
  'pipewire-alsa',
  'pipewire-codec-aptx',
  'pipewire-gstreamer',
  'pipewire-jack-audio-connection-kit-libs',
  'pipewire-pulseaudio',
  'pipewire-utils',
  'pitivi',
  'pixi',
  'plasma-breeze',
  'plasma-desktop',
  'plasma-desktop-doc',
  'plasma-disks',
  'plasma-drkonqi',
  'plasma-nm',
  'plasma-nm-l2tp',
  'plasma-nm-openconnect',
  'plasma-nm-openswan',
  'plasma-nm-openvpn',
  'plasma-nm-pptp',
  'plasma-nm-vpnc',
  'plasma-pa',
  'plasma-print-manager',
  'plasma-systemmonitor',
  'plasma-thunderbolt',
  'plasma-vault',
  'plasma-workspace',
  'plasma-workspace-wallpapers',
  'plocate',
  'plymouth',
  'plymouth-plugin-script',
  'plymouth-system-theme',
  'podman',
  'podman-compose',
  'podman-sequoia',
  'policycoreutils',
  'polkit-kde',
  'portmaster',
  'postman',
  'powertop',
  'ppp',
  'pptp',
  'prefixdevname',
  'procps-ng',
  'procs',
  'proton-vpn-gnome-desktop',
  'protonvpn-stable-release',
  'psacct',
  'pulseaudio-libs',
  'python3-devel',
  'python3-googleapis-common-protos',
  'python3-grpcio',
  'python3-hid',
  'python3-jsonschema',
  'python3-jsonschema-specifications',
  'python3-pip',
  'python3-pyasn',
  'python3-qt5',
  'python3-referencing',
  'python3-rpds-py',
  'python3-slugify',
  'python3-termcolor',
  'python3-tqdm',
  'python3-vapoursynth',
  'qBittorrent-Enhanced-Edition',
  'qemu',
  'qemu-device-display-qxl',
  'qemu-guest-agent',
  'qman',
  'qpdf',
  'qrca',
  'qt6ct',
  'quodlibet',
  'quota',
  'qwinff',
  'rar',
  'realmd',
  'realtek-firmware',
  'remmina',
  'remmina-plugins-rdp',
  'renamemytvseries',
  'resources',
  'riseup-vpn',
  'rit-rachana-fonts',
  'rootfiles',
  'rpkg',
  'rpm',
  'rpmfusion-free-release',
  'rpmfusion-nonfree-release',
  'rsms-inter-fonts',
  'rsync',
  'rsyslog',
  'rust',
  'rust2rpm',
  'rust2rpm-helper',
  'ryzenadj',
  'samba-client',
  'samba-common-libs',
  'samba-common-tools',
  'samba-libs',
  'samba-usershares',
  'samba-winbind',
  'samba-winbind-clients',
  'samba-winbind-modules',
  'sane-backends-libs',
  'scrcpy',
  'scx-tools',
  'sddm',
  'sddm-breeze',
  'sddm-kcm',
  'sddm-wayland-plasma',
  'sdgyrodsu',
  'seahorse',
  'selinux-policy-targeted',
  'setup',
  'shadow-utils',
  'shim-ia32',
  'shim-x64',
  'signon-kwallet-extension',
  'simdutf',
  'skopeo',
  'sly',
  'smartmontools',
  'snapd',
  'sos',
  'sourcegit',
  'spectacle',
  'speech-dispatcher',
  'spice-vdagent',
  'spice-webdavd',
  'sssd-common',
  'sssd-kcm',
  'sssd-proxy',
  'stacher',
  'strawberry',
  'subtitlecomposer-git',
  'subtitleeditor',
  'subversion',
  'sudo',
  'symlinks',
  'syncthing',
  'syncthingtray-qt6',
  'syslinux',
  'system-config-language',
  'system-config-printer-udev',
  'systemd',
  'systemd-container',
  'systemd-oomd-defaults',
  'systemd-resolved',
  'systemd-udev',
  'systemtap',
  'tar',
  'tcp_wrappers-libs',
  'tcpdump',
  'tealdeer',
  'teamd',
  'temurin-21-jdk',
  'termora',
  'terra-release',
  'texlive-dvipng',
  'texlive-dvisvgm',
  'texlive-scheme-basic',
  'thunderbird',
  'time',
  'timeshift',
  'tiwilink-firmware',
  'tixati',
  'tlp',
  'tlp-rdw',
  'tlp-release',
  'topgrade',
  'torrent-file-editor',
  'traceroute',
  'tree',
  'trippy',
  'ubuntu-family-fonts',
  'udisks2',
  'umu-launcher',
  'unixODBC',
  'unzip',
  'urw-base35-bookman-fonts',
  'urw-base35-c059-fonts',
  'urw-base35-d050000l-fonts',
  'urw-base35-fonts',
  'urw-base35-gothic-fonts',
  'urw-base35-nimbus-mono-ps-fonts',
  'urw-base35-nimbus-roman-fonts',
  'urw-base35-nimbus-sans-fonts',
  'urw-base35-p052-fonts',
  'urw-base35-standard-symbols-ps-fonts',
  'urw-base35-z003-fonts',
  'usage-cli',
  'usb_modeswitch',
  'usbutils',
  'util-linux',
  'vapoursynth-tools',
  'ventoy',
  'veracrypt',
  'vim-enhanced',
  'vim-minimal',
  'virt-manager',
  'virtualbox-guest-additions',
  'vkBasalt',
  'vlc',
  'vlc-plugin-gstreamer',
  'vulkan-tools',
  'wasistlos',
  'waterfox',
  'wezterm',
  'wget1',
  'wget1-wget',
  'wget2',
  'which',
  'whois',
  'windscribe',
  'windsurf',
  'winehq-staging',
  'winetricks',
  'wireplumber',
  'wireshark',
  'wl-clipboard',
  'words',
  'wpa_supplicant',
  'x264-libs',
  'x265-libs',
  'xclip',
  'xfsprogs',
  'xnconvert',
  'xnviewmp',
  'xrdp',
  'xwaylandvideobridge',
  'yazi',
  'youki',
  'yumex',
  'zed',
  'zen-browser',
  'zenity',
  'zip',
  'zoxide',
  'zram-generator-defaults'
]

# Packages to be installed via Flatpak.
[managers.flatpak]
items = [
  'app.drey.EarTag',
  'be.alexandervanhee.gradia',
  # 'com.collabora.Office',
  'com.github.finefindus.eyedropper',
  'com.github.jeromerobert.pdfarranger',
  'com.icons8.Lunacy',
  'com.ktechpit.whatsie',
  'com.rtosta.zapzap',
  'com.termius.Termius',
  'com.thincast.client',
  'com.warlordsoftwares.formatlab',
  'de.leopoldluley.Clapgrep',
  'dev.geopjr.Turntable',
  'info.smplayer.SMPlayer',
  'io.github.CardiJey.schulrechner',
  'io.github.JakubMelka.Pdf4qt',
  'io.github.Qalculate.qalculate-qt',
  'io.github.amit9838.mousam',
  'io.github.giantpinkrobots.flatsweep',
  'io.github.giantpinkrobots.varia',
  'io.github.vikdevelop.SaveDesktop',
  'io.github.wartybix.Constrict',
  'io.photoflare.photoflare',
  'io.sourceforge.Pixelitor',
  'net.code_industry.MasterPDFEditor',
  'net.codelogistics.letters',
  'net.fasterland.converseen',
  'net.puddletag.puddletag',
  'org.flathub.flatpak-external-data-checker',
  'org.freedesktop.LinuxAudio.Plugins.TAP',
  'org.freedesktop.LinuxAudio.Plugins.swh',
  'org.freedesktop.Platform',
  'org.freedesktop.Platform',
  'org.freedesktop.Platform.GL.default',
  'org.freedesktop.Platform.VAAPI.Intel',
  'org.freedesktop.Platform.codecs-extra',
  'org.freedesktop.Platform.ffmpeg-full',
  'org.freedesktop.Platform.openh264',
  'org.freedesktop.Sdk',
  'org.freedesktop.Sdk',
  'org.gnome.Lollypop',
  'org.gnome.Loupe',
  'org.gnome.Platform',
  'org.gnome.gitlab.YaLTeR.VideoTrimmer',
  'org.gtk.Gtk3theme.adw-gtk3-dark',
  'org.kde.Platform',
  'org.kde.kdenlive',
  'org.kde.kid3',
  'org.kde.koko',
  'org.kde.krdc',
  'org.kde.krita',
  'org.kde.labplot',
  'org.nickvision.tagger',
  'org.nickvision.tubeconverter',
  'org.shotcut.Shotcut',
  'org.speedcrunch.SpeedCrunch',
  'org.subtitld.Subtitld',
  'page.codeberg.JakobDev.jdDesktopEntryEdit',
  'page.codeberg.JakobDev.jdSystemMonitor',
  're.sonny.Junction',
  'uno.platform.uno-calculator',
  'us.zoom.Zoom'
]

# Packages to be installed via Cargo.
[managers.cargo]
items = [
  'atem',
  'cargo-clean',
  'metapac',
  'rebos'
]
