# Flatpak

add = "sudo flatpak install -y flathub #:?"
remove = "sudo flatpak uninstall -y #:?"
upgrade = "sudo flatpak update -y #:?"

plural_name = "flatpaks"

hook_name = "flatpaks"

[config]
many_args = true
