# --------------------------- #
#    Manager Configuration    #
# --------------------------- #

# Make sure to enter the exact command you use as the normal user!
# That means including 'sudo' or 'doas' or whatever if the command needs it.
# Where you would put items, enter '#:?'.

# Example: add = "sudo apt install #:?"

add = "sudo dnf --setopt=install_weak_deps=False install -y #:?" # Example: sudo apt install #:?
remove = "sudo dnf --setopt=install_weak_deps=False remove -y #:?" # Example: sudo apt remove #:?
sync = "sudo dnf check-update --refresh -y" # Example: sudo apt update
upgrade = "sudo --setopt=install_weak_deps=False dnf upgrade -y #:?" # Example: sudo apt upgrade

plural_name = "system packages"

hook_name = "system_packages" # This is used in hooks. (Example: post_system_packages_add)

# ------------------------------- #
#    Additional configuration.    #
# ------------------------------- #

# many_args = BOOL: Can you supply many items as an argument? Example: 'sudo apt install git vim wget'

[config]
many_args = true
